import os
import json
import logging
import requests
from datetime import datetime, timedelta
from dotenv import load_dotenv

# Load credentials
load_dotenv()

FB_PAGE_ID = os.getenv("FB_PAGE_ID")
FB_ACCESS_TOKEN = os.getenv("FB_ACCESS_TOKEN")
VAULT_PATH = os.path.join(os.environ.get("USERPROFILE"), "AI_Employee_Vault")
BRIEFINGS_PATH = os.path.join(VAULT_PATH, "Briefings")
NEEDS_ACTION_PATH = os.path.join(VAULT_PATH, "Needs_Action")

# Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("facebook_summary")

def get_weekly_stats():
    base_url = "https://graph.facebook.com/v19.0"
    since = (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')
    
    # 1. Reach
    insights_url = f"{base_url}/{FB_PAGE_ID}/insights?metric=page_impressions_unique&period=day&since={since}&access_token={FB_ACCESS_TOKEN}"
    insights = requests.get(insights_url).json()
    total_reach = 0
    if "data" in insights and len(insights["data"]) > 0:
        for entry in insights["data"][0].get("values", []):
            total_reach += entry.get("value", 0)

    # 2. Posts and Engagement
    posts_url = f"{base_url}/{FB_PAGE_ID}/posts?fields=id,message,created_time,likes.summary(true),comments.summary(true),shares&limit=50&access_token={FB_ACCESS_TOKEN}"
    posts_data = requests.get(posts_url).json().get("data", [])
    
    weekly_posts = []
    for p in posts_data:
        created_at = datetime.strptime(p["created_time"].split("+")[0], "%Y-%m-%dT%H:%M:%S")
        if created_at > datetime.now() - timedelta(days=7):
            weekly_posts.append(p)
            
    top_post = "None"
    max_eng = -1
    for p in weekly_posts:
        likes = p.get("likes", {}).get("summary", {}).get("total_count", 0)
        comments = p.get("comments", {}).get("summary", {}).get("total_count", 0)
        shares = p.get("shares", {}).get("count", 0)
        eng = likes + comments + shares
        if eng > max_eng:
            max_eng = eng
            top_post = p.get("message", p.get("id"))[:100] + "..."

    # 3. New Followers (Page Fans)
    fans_url = f"{base_url}/{FB_PAGE_ID}/insights?metric=page_fans&period=lifetime&since={since}&access_token={FB_ACCESS_TOKEN}"
    fans_data = requests.get(fans_url).json().get("data", [])
    new_followers = 0
    if len(fans_data) > 0:
        values = fans_data[0].get("values", [])
        if len(values) >= 2:
            new_followers = values[-1]["value"] - values[0]["value"]

    # 4. Pending Replies
    pending_replies = 0
    if os.path.exists(NEEDS_ACTION_PATH):
        pending_replies = len([f for f in os.listdir(NEEDS_ACTION_PATH) if f.startswith("FACEBOOK_")])

    return {
        "posts_published": len(weekly_posts),
        "total_reach": total_reach,
        "top_post": top_post,
        "new_followers": new_followers,
        "pending_replies": pending_replies
    }

def generate_report():
    stats = get_weekly_stats()
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"Facebook_Weekly_{date_str}.md"
    file_path = os.path.join(BRIEFINGS_PATH, filename)
    
    content = f"""# Facebook Weekly Briefing — {date_str}

## 📊 Summary Stats
- **Posts Published:** {stats['posts_published']}
- **Total Reach:** {stats['total_reach']}
- **New Followers:** {stats['new_followers']}
- **Pending Replies:** {stats['pending_replies']}

## 🏆 Top Performing Post
{stats['top_post']}

---
*Generated by AI Employee Gold v1.0 — {datetime.now().isoformat()}*
"""
    os.makedirs(BRIEFINGS_PATH, exist_ok=True)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info(f"Summary report generated: {filename}")

if __name__ == "__main__":
    generate_report()
