import os
import json
import logging
import requests
from datetime import datetime, timedelta
from dotenv import load_dotenv

# Load credentials
load_dotenv()

IG_ACCOUNT_ID = os.getenv("IG_ACCOUNT_ID")
IG_ACCESS_TOKEN = os.getenv("IG_ACCESS_TOKEN")
VAULT_PATH = os.path.join(os.environ.get("USERPROFILE"), "AI_Employee_Vault")
BRIEFINGS_PATH = os.path.join(VAULT_PATH, "Briefings")
NEEDS_ACTION_PATH = os.path.join(VAULT_PATH, "Needs_Action")

# Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("instagram_summary")

def get_weekly_stats():
    base_url = "https://graph.facebook.com/v19.0"
    since = (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')
    until = datetime.now().strftime('%Y-%m-%d')
    
    # 1. Account Info & Following
    acc_url = f"{base_url}/{IG_ACCOUNT_ID}?fields=followers_count,media_count&access_token={IG_ACCESS_TOKEN}"
    acc_data = requests.get(acc_url).json()
    
    # 2. Insights for reach and growth
    insights_url = f"{base_url}/{IG_ACCOUNT_ID}/insights?metric=reach,follower_count&period=day&since={since}&until={until}&access_token={IG_ACCESS_TOKEN}"
    insights_res = requests.get(insights_url).json()
    
    total_reach = 0
    follower_growth = 0
    if "data" in insights_res:
        for metric in insights_res["data"]:
            if metric["name"] == "reach":
                total_reach = sum(v["value"] for v in metric["values"])
            if metric["name"] == "follower_count":
                follower_growth = sum(v["value"] for v in metric["values"])

    # 3. Media analysis
    media_url = f"{base_url}/{IG_ACCOUNT_ID}/media?fields=id,media_type,timestamp,like_count,comments_count&access_token={IG_ACCESS_TOKEN}"
    media_data = requests.get(media_url).json().get("data", [])
    
    weekly_media = []
    reels_count = 0
    posts_count = 0
    max_eng = -1
    top_post_id = None
    
    for m in media_data:
        ts = datetime.strptime(m["timestamp"].split("+")[0], "%Y-%m-%dT%H:%M:%S")
        if ts > datetime.now() - timedelta(days=7):
            weekly_media.append(m)
            if m["media_type"] == "VIDEO": reels_count += 1
            else: posts_count += 1
            
            eng = m.get("like_count", 0) + m.get("comments_count", 0)
            if eng > max_eng:
                max_eng = eng
                top_post_id = m["id"]

    # 4. Pending Replies
    pending_replies = 0
    if os.path.exists(NEEDS_ACTION_PATH):
        pending_replies = len([f for f in os.listdir(NEEDS_ACTION_PATH) if f.startswith("INSTAGRAM_")])

    engagement_rate = round((max_eng / max(total_reach, 1)) * 100, 2) if top_post_id else 0

    return {
        "posts_published": posts_count,
        "reels_published": reels_count,
        "follower_growth": follower_growth,
        "total_reach": total_reach,
        "top_post_id": top_post_id,
        "engagement_rate": f"{engagement_rate}%",
        "pending_replies": pending_replies
    }

def generate_report():
    stats = get_weekly_stats()
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"Instagram_Weekly_{date_str}.md"
    file_path = os.path.join(BRIEFINGS_PATH, filename)
    
    content = f"""# Instagram Weekly Briefing — {date_str}

## 📈 Performance Summary
- **Posts Published:** {stats['posts_published']}
- **Reels Published:** {stats['reels_published']}
- **Follower Growth:** {stats['follower_growth']}
- **Total Reach:** {stats['total_reach']}
- **Engagement Rate:** {stats['engagement_rate']}
- **Pending Replies:** {stats['pending_replies']}

## 🌟 Top Post this Week
Post ID: {stats['top_post_id'] or 'N/A'}

---
*Generated by AI Employee Gold v1.0 — {datetime.now().isoformat()}*
"""
    os.makedirs(BRIEFINGS_PATH, exist_ok=True)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info(f"Summary report generated: {filename}")

if __name__ == "__main__":
    generate_report()
