import os
import json
import logging
import tweepy
from datetime import datetime, timedelta
from dotenv import load_dotenv

# Load credentials
load_dotenv()

API_KEY = os.getenv("TWITTER_API_KEY")
API_SECRET = os.getenv("TWITTER_API_SECRET")
ACCESS_TOKEN = os.getenv("TWITTER_ACCESS_TOKEN")
ACCESS_SECRET = os.getenv("TWITTER_ACCESS_SECRET")
BEARER_TOKEN = os.getenv("TWITTER_BEARER_TOKEN")

VAULT_PATH = os.path.join(os.environ.get("USERPROFILE"), "AI_Employee_Vault")
BRIEFINGS_PATH = os.path.join(VAULT_PATH, "Briefings")
NEEDS_ACTION_PATH = os.path.join(VAULT_PATH, "Needs_Action")

# Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("twitter_summary")

class TwitterSummary:
    def __init__(self):
        try:
            self.client = tweepy.Client(bearer_token=BEARER_TOKEN)
            # We need the user ID. We can get it from the bearer token or access tokens.
            # Usually easier to just use the authenticated client.
            self.auth_client = tweepy.Client(
                consumer_key=API_KEY, consumer_secret=API_SECRET,
                access_token=ACCESS_TOKEN, access_token_secret=ACCESS_SECRET
            )
            self.me = self.auth_client.get_me().data
        except Exception as e:
            logger.error(f"Twitter Init Error: {e}")
            self.client = None

    def get_stats(self):
        if not self.me: return {}
        
        start_time = (datetime.utcnow() - timedelta(days=7)).isoformat() + "Z"
        
        # 1. Tweets and Impressions
        tweets = self.auth_client.get_users_tweets(
            id=self.me.id,
            start_time=start_time,
            tweet_fields=["public_metrics", "created_at", "text"]
        )
        
        tweets_data = tweets.data if tweets.data else []
        total_impressions = sum(t.public_metrics.get("impression_count", 0) for t in tweets_data)
        
        top_tweet = "None"
        max_likes = -1
        for t in tweets_data:
            likes = t.public_metrics.get("like_count", 0)
            if likes > max_likes:
                max_likes = likes
                top_tweet = t.text[:100] + "..."

        # 2. Followers
        user_data = self.auth_client.get_user(id=self.me.id, user_fields=["public_metrics"])
        followers_count = user_data.data.public_metrics["followers_count"]

        # 3. Mentions
        mentions = self.auth_client.get_users_mentions(id=self.me.id, start_time=start_time)
        mentions_count = len(mentions.data) if mentions.data else 0

        # 4. Pending Replies
        pending_replies = 0
        if os.path.exists(NEEDS_ACTION_PATH):
            pending_replies = len([f for f in os.listdir(NEEDS_ACTION_PATH) if f.startswith("TWITTER_")])

        return {
            "tweets_published": len(tweets_data),
            "total_impressions": total_impressions,
            "followers": followers_count,
            "top_tweet": top_tweet,
            "mentions_count": mentions_count,
            "pending_replies": pending_replies
        }

def generate_report():
    summary = TwitterSummary()
    stats = summary.get_stats()
    if not stats:
        logger.error("Failed to fetch Twitter stats")
        return

    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"Twitter_Weekly_{date_str}.md"
    file_path = os.path.join(BRIEFINGS_PATH, filename)
    
    content = f"""# Twitter/X Weekly Briefing — {date_str}

## 📊 Summary Stats
- **Tweets Published:** {stats['tweets_published']}
- **Total Impressions:** {stats['total_impressions']}
- **Current Followers:** {stats['followers']}
- **Mentions this Week:** {stats['mentions_count']}
- **Pending Replies:** {stats['pending_replies']}

## 🏆 Top Tweet
{stats['top_tweet']}

---
*Generated by AI Employee Gold v1.0 — {datetime.now().isoformat()}*
"""
    os.makedirs(BRIEFINGS_PATH, exist_ok=True)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info(f"Summary report generated: {filename}")

if __name__ == "__main__":
    generate_report()
