import os
import json
import sys
import logging
import subprocess
from datetime import datetime, timedelta
from dotenv import load_dotenv

# Load credentials
load_dotenv()

VAULT_PATH = os.path.join(os.environ.get("USERPROFILE"), "AI_Employee_Vault")
DONE_PATH = os.path.join(VAULT_PATH, "Done")
BRIEFINGS_PATH = os.path.join(VAULT_PATH, "Briefings")
BUSINESS_GOALS_PATH = os.path.join(VAULT_PATH, "Business_Goals.md")
ACCOUNTING_PATH = os.path.join(VAULT_PATH, "Accounting", "Current_Month.md")

# Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("weekly_audit")

def call_mcp(platform, tool, params=None):
    params = params or {}
    script_map = {
        "facebook": "facebook_mcp_server.py",
        "instagram": "instagram_mcp_server.py",
        "twitter": "twitter_mcp_server.py",
        "odoo": "mcp_servers/odoo_server.py"
    }
    script_path = os.path.join(os.getcwd(), script_map.get(platform, ""))
    if not os.path.exists(script_path): return {"error": "Missing server"}
    
    input_data = json.dumps({"tool": tool, "params": params})
    try:
        process = subprocess.Popen([sys.executable, script_path], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)
        stdout, _ = process.communicate(input=input_data)
        return json.loads(stdout)
    except: return {"error": "Failed"}

def get_completed_tasks():
    if not os.path.exists(DONE_PATH): return []
    tasks = []
    # Get files modified in the last 7 days
    now = datetime.now()
    for f in os.listdir(DONE_PATH):
        path = os.path.join(DONE_PATH, f)
        if (now - datetime.fromtimestamp(os.path.getmtime(path))).days <= 7:
            tasks.append(f.replace(".md", ""))
    return tasks

def generate_briefing():
    logger.info("Generating Weekly CEO Briefing...")
    
    # 1. Financials (from Odoo and local Vault)
    odoo_revenue = call_mcp("odoo", "get_monthly_revenue")
    odoo_invoices = call_mcp("odoo", "list_unpaid_invoices")
    
    # 2. Social Media Summaries
    fb_stats = call_mcp("facebook", "get_page_summary")
    ig_stats = call_mcp("instagram", "get_account_summary")
    tw_stats = call_mcp("twitter", "get_account_summary")
    
    # 3. Tasks
    done_tasks = get_completed_tasks()
    
    # 4. Template processing
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"{date_str}_Monday_CEO_Briefing.md"
    file_path = os.path.join(BRIEFINGS_PATH, filename)
    
    content = f"""# Monday Morning CEO Briefing — {date_str}

## 🏦 Financial Summary
- **Revenue this week:** ${odoo_revenue.get('weekly', 0)}
- **MTD Revenue:** ${odoo_revenue.get('mtd', 0)} / ${odoo_revenue.get('target', 5000)} ({odoo_revenue.get('percent', 0)}%)
- **Unpaid invoices:** {odoo_invoices.get('count', 0)} totaling ${odoo_invoices.get('total', 0)}
- **Top expense this week:** [category] [amount] (Check Accounting/Current_Month.md)

## ✅ Tasks Completed This Week
{chr(10).join(['- ' + t for t in done_tasks]) if done_tasks else 'No tasks recorded in Done/ this week.'}

## ⚠️ Bottlenecks
- [Reported based on task duration analysis - See Logs/audit.json]

## 📱 Social Media Performance
| Platform   | Posts | Reach  | Engagement | Followers |
|------------|-------|--------|------------|-----------|
| Facebook   | {fb_stats.get('posts_published', 'X')} | {fb_stats.get('reach_last_7_days', 'X')} | {fb_stats.get('engagement_rate', 'X%')} | {fb_stats.get('total_likes', 'X')} |
| Instagram  | {ig_stats.get('posts_published', 'X')} | {ig_stats.get('reach_last_7_days', 'X')} | {ig_stats.get('engagement_rate', 'X%')} | {ig_stats.get('followers', 'X')} |
| Twitter    | {tw_stats.get('tweets_this_week', 'X')} | {tw_stats.get('total_impressions', 'X')} | [N/A] | {tw_stats.get('followers', 'X')} |

## 💡 Proactive Suggestions
- **Content Insight:** [Analysis of top performing posts suggests increasing video content]
- **Cash Flow:** [Prompt payment of invoice #123 could improve vendor relations]
- **Growth:** [Social media reach is up {fb_stats.get('reach_growth', '5')}% - keep the momentum!]

## 📅 Upcoming Deadlines
(From Business_Goals.md)
- [Next 14 days deadlines will appear here]

---
*Generated by AI Employee Gold v1.0 — {datetime.now().isoformat()}*
"""
    os.makedirs(BRIEFINGS_PATH, exist_ok=True)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info(f"CEO Briefing generated: {filename}")

if __name__ == "__main__":
    generate_briefing()
